/**
 * Agent Framework Types
 *
 * Core types and interfaces for the Ophan multi-agent architecture.
 * Each agent operates in the Two-Loop Paradigm with its own (G,C) pair.
 */

import type { Proposal, OphanConfig } from '../../types/index.js';

/**
 * Unique identifier for an agent type
 */
export type AgentId = 'task-agent' | 'context-agent' | string;

/**
 * Configuration for an agent's (G,C) pair
 */
export interface AgentGuidanceConfig {
  /** Guideline files relative to .ophan/guidelines/ */
  guidelineFiles: string[];
  /** Criteria files relative to .ophan/criteria/ */
  criteriaFiles: string[];
}

/**
 * Metrics computed by an agent's evaluation
 */
export interface AgentMetrics {
  /** Name of the metric */
  name: string;
  /** Current value */
  value: number;
  /** Target value (if applicable) */
  target?: number;
  /** Whether the metric is passing */
  passed: boolean;
}

/**
 * Result of an agent's outer loop analysis
 */
export interface AgentOuterLoopResult {
  /** Proposals generated by this agent */
  proposals: Proposal[];
  /** Metrics computed during analysis */
  metrics: AgentMetrics[];
  /** Summary message for logging */
  summary: string;
}

/**
 * Options passed to agent initialization
 */
export interface AgentOptions {
  /** Path to the project root */
  projectRoot: string;
  /** Path to the .ophan directory */
  ophanDir: string;
  /** Ophan configuration */
  config: OphanConfig;
  /** Progress callback for logging */
  onProgress?: (message: string) => void;
}

/**
 * Base interface that all Ophan agents must implement.
 *
 * Each agent:
 * - Has a unique ID and display name
 * - Owns a (G,C) pair (guidelines and criteria)
 * - Can generate proposals during the outer loop
 * - Can compute metrics for self-evaluation
 */
export interface BaseAgent {
  /** Unique identifier for this agent */
  readonly id: AgentId;

  /** Human-readable name */
  readonly name: string;

  /** Description of what this agent does */
  readonly description: string;

  /** Configuration for this agent's (G,C) pair */
  readonly guidance: AgentGuidanceConfig;

  /**
   * Initialize the agent (called once at startup)
   */
  initialize(options: AgentOptions): Promise<void>;

  /**
   * Execute the agent's outer loop analysis.
   * Called during `ophan review` to generate proposals.
   *
   * @param lookbackDays - Number of days to analyze
   * @param autoApplyGuidelines - Whether to auto-apply guideline changes
   * @returns Proposals and metrics from this agent
   */
  runOuterLoop(
    lookbackDays: number,
    autoApplyGuidelines: boolean
  ): Promise<AgentOuterLoopResult>;

  /**
   * Get current metrics for this agent.
   * Used for status display and monitoring.
   */
  getMetrics(): Promise<AgentMetrics[]>;

  /**
   * Log a message using the configured progress callback
   */
  log(message: string): void;
}

/**
 * Extended interface for agents that can execute tasks (inner loop).
 * Not all agents have an inner loop - some only analyze and propose.
 */
export interface ExecutableAgent extends BaseAgent {
  /**
   * Whether this agent can execute tasks
   */
  readonly canExecuteTasks: true;

  /**
   * Execute a task through the inner loop
   */
  executeTask(taskDescription: string): Promise<ExecutionResult>;
}

/**
 * Result of task execution
 */
export interface ExecutionResult {
  /** Whether the task converged successfully */
  success: boolean;
  /** Number of iterations used */
  iterations: number;
  /** Total cost in USD */
  cost: number;
  /** Output/summary from the execution */
  output: string;
  /** Any learnings extracted */
  learnings: string[];
}

/**
 * Type guard to check if an agent can execute tasks
 */
export function isExecutableAgent(agent: BaseAgent): agent is ExecutableAgent {
  return 'canExecuteTasks' in agent && agent.canExecuteTasks === true;
}
